//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuxEmergencial
{
    using System;
    using System.Collections.Generic;
    
    public partial class auxemergencial
    {
        public int id { get; set; }
        public Nullable<int> nirsas { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string cpf { get; set; }
        public string cep { get; set; }
        public string rua { get; set; }
        public string numero { get; set; }
        public string bairro { get; set; }
        public string complemento { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string telefone { get; set; }
        public string pmtr { get; set; }
        public string bee { get; set; }
        public string cesta { get; set; }
        public string bf { get; set; }
        public string bpc { get; set; }
        public string observacoes { get; set; }
        public string urgente { get; set; }
        public string finalidade { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
    }
}
